### ISSUE TITLE
Various job queue improvements

### ISSUE THREAD

**Issue by mpaddock** [UK-AS-HIVE/meteor-job-queue#1]
1. Throw out the 'pipelines' concept and just make everything discrete jobs. Jobs can schedule other jobs in a tree, but remove DAG functionality.
2. Simplify the calls for scheduling a job.
3. Remove UploadProcessor, since the functionality is replicated in hive:upload.
4. Use settings to determine behavior instead of port number.
5. Clean up code and cut out any cruft.

**Comment by noahadler** [comment]
I went ahead and removed the UploadProcessor and related code, so 3 should be done as of fac77e9

**Comment by noahadler** [comment]
Most of this is done, going in the workers direction.
